/*
 * Automatically generated by jrpcgen 1.1.6 on 24-8-23 上午9:09
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
package xyz.hooy.vxi11.rpc.idl;
import org.acplt.oncrpc.*;
import java.io.IOException;

/** TODO */
public class Create_LinkParms implements XdrAble {
    /** TODO */
    public int clientId;
    /** TODO */
    public boolean lockDevice;
    /** TODO */
    public int lock_timeout;
    /** TODO */
    public String device;

    public Create_LinkParms() {
    }

    public Create_LinkParms(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public Create_LinkParms(int clientId, boolean lockDevice, int lock_timeout,
           String device) {
        this.clientId = clientId;
        this.lockDevice = lockDevice;
        this.lock_timeout = lock_timeout;
        this.device = device;
    }

    @Override
    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        xdr.xdrEncodeInt(clientId);
        xdr.xdrEncodeBoolean(lockDevice);
        xdr.xdrEncodeInt(lock_timeout);
        xdr.xdrEncodeString(device);
    }

    @Override
    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        clientId = xdr.xdrDecodeInt();
        lockDevice = xdr.xdrDecodeBoolean();
        lock_timeout = xdr.xdrDecodeInt();
        device = xdr.xdrDecodeString();
    }

    @Override
    public String toString() {
        return "Create_LinkParms ["
        + "clientId=" + clientId + ", "
        + "lockDevice=" + lockDevice + ", "
        + "lock_timeout=" + lock_timeout + ", "
        + "device=" + device
        + "]";
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) return true;
        if (obj == null) return false;
        if (getClass() != obj.getClass()) return false;
        Create_LinkParms other = (Create_LinkParms)obj;
        if (this.clientId != other.clientId) return false;
        if (this.lockDevice != other.lockDevice) return false;
        if (this.lock_timeout != other.lock_timeout) return false;
        if (! java.util.Objects.equals(this.device, other.device)) return false;
        return true;
    }

    @Override
    public int hashCode() {
        return XdrHashCode.hashCode(this);
    }

}
// End of Create_LinkParms.java
