/*
 * Automatically generated by jrpcgen 1.1.6 on 24-8-23 上午9:09
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
package xyz.hooy.vxi11.rpc.idl;
import org.acplt.oncrpc.*;
import java.io.IOException;

/** TODO */
public class Device_SrqParms implements XdrAble {
    /** TODO */
    public byte[] handle;

    public Device_SrqParms() {
    }

    public Device_SrqParms(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public Device_SrqParms(byte[] handle) {
        this.handle = handle;
    }

    @Override
    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        xdr.xdrEncodeDynamicOpaque(handle);
    }

    @Override
    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        handle = xdr.xdrDecodeDynamicOpaque();
    }

    @Override
    public String toString() {
        return "Device_SrqParms ["
        + "handle=" + java.util.Arrays.toString(handle)
        + "]";
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) return true;
        if (obj == null) return false;
        if (getClass() != obj.getClass()) return false;
        Device_SrqParms other = (Device_SrqParms)obj;
        if (! java.util.Arrays.equals(this.handle, other.handle)) return false;
        return true;
    }

    @Override
    public int hashCode() {
        return XdrHashCode.hashCode(this);
    }

}
// End of Device_SrqParms.java
