/*
 * Automatically generated by jrpcgen 1.1.6 on 24-8-23 上午9:09
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
package xyz.hooy.vxi11.rpc.idl;
import org.acplt.oncrpc.*;
import java.io.IOException;

/** TODO */
public class Device_LockParms implements XdrAble {
    /** TODO */
    public Device_Link lid;
    /** TODO */
    public Device_Flags flags;
    /** TODO */
    public int lock_timeout;

    public Device_LockParms() {
    }

    public Device_LockParms(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public Device_LockParms(Device_Link lid, Device_Flags flags,
           int lock_timeout) {
        this.lid = lid;
        this.flags = flags;
        this.lock_timeout = lock_timeout;
    }

    @Override
    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        lid.xdrEncode(xdr);
        flags.xdrEncode(xdr);
        xdr.xdrEncodeInt(lock_timeout);
    }

    @Override
    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        lid = new Device_Link(xdr);
        flags = new Device_Flags(xdr);
        lock_timeout = xdr.xdrDecodeInt();
    }

    @Override
    public String toString() {
        return "Device_LockParms ["
        + "lid=" + lid + ", "
        + "flags=" + flags + ", "
        + "lock_timeout=" + lock_timeout
        + "]";
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) return true;
        if (obj == null) return false;
        if (getClass() != obj.getClass()) return false;
        Device_LockParms other = (Device_LockParms)obj;
        if (! java.util.Objects.equals(this.lid, other.lid)) return false;
        if (! java.util.Objects.equals(this.flags, other.flags)) return false;
        if (this.lock_timeout != other.lock_timeout) return false;
        return true;
    }

    @Override
    public int hashCode() {
        return XdrHashCode.hashCode(this);
    }

}
// End of Device_LockParms.java
