/*
 * Automatically generated by jrpcgen 1.1.6 on 24-8-23 上午9:09
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
package xyz.hooy.vxi11.rpc.idl;
import org.acplt.oncrpc.*;
import java.io.IOException;

/** TODO */
public class Device_RemoteFunc implements XdrAble {
    /** TODO */
    public int hostAddr;
    /** TODO */
    public int hostPort;
    /** TODO */
    public int progNum;
    /** TODO */
    public int progVers;
    /** TODO */
    public Device_AddrFamily progFamily;

    public Device_RemoteFunc() {
    }

    public Device_RemoteFunc(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public Device_RemoteFunc(int hostAddr, int hostPort, int progNum,
           int progVers, Device_AddrFamily progFamily) {
        this.hostAddr = hostAddr;
        this.hostPort = hostPort;
        this.progNum = progNum;
        this.progVers = progVers;
        this.progFamily = progFamily;
    }

    @Override
    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        xdr.xdrEncodeInt(hostAddr);
        xdr.xdrEncodeInt(hostPort);
        xdr.xdrEncodeInt(progNum);
        xdr.xdrEncodeInt(progVers);
        xdr.xdrEncodeInt(progFamily.getEncoding());
    }

    @Override
    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        hostAddr = xdr.xdrDecodeInt();
        hostPort = xdr.xdrDecodeInt();
        progNum = xdr.xdrDecodeInt();
        progVers = xdr.xdrDecodeInt();
        progFamily = XdrEnum.create(Device_AddrFamily.DEVICE_TCP, xdr);
    }

    @Override
    public String toString() {
        return "Device_RemoteFunc ["
        + "hostAddr=" + hostAddr + ", "
        + "hostPort=" + hostPort + ", "
        + "progNum=" + progNum + ", "
        + "progVers=" + progVers + ", "
        + "progFamily=" + progFamily
        + "]";
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) return true;
        if (obj == null) return false;
        if (getClass() != obj.getClass()) return false;
        Device_RemoteFunc other = (Device_RemoteFunc)obj;
        if (this.hostAddr != other.hostAddr) return false;
        if (this.hostPort != other.hostPort) return false;
        if (this.progNum != other.progNum) return false;
        if (this.progVers != other.progVers) return false;
        if (! java.util.Objects.equals(this.progFamily, other.progFamily)) return false;
        return true;
    }

    @Override
    public int hashCode() {
        return XdrHashCode.hashCode(this);
    }

}
// End of Device_RemoteFunc.java
