/*
 * Automatically generated by jrpcgen 1.1.6 on 24-8-23 上午9:09
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
package xyz.hooy.vxi11.rpc.idl;
import org.acplt.oncrpc.*;
import java.io.IOException;

/** TODO */
public class Device_WriteResp implements XdrAble {
    /** TODO */
    public Device_ErrorCode error;
    /** TODO */
    public int size;

    public Device_WriteResp() {
    }

    public Device_WriteResp(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public Device_WriteResp(Device_ErrorCode error, int size) {
        this.error = error;
        this.size = size;
    }

    @Override
    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        error.xdrEncode(xdr);
        xdr.xdrEncodeInt(size);
    }

    @Override
    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        error = new Device_ErrorCode(xdr);
        size = xdr.xdrDecodeInt();
    }

    @Override
    public String toString() {
        return "Device_WriteResp ["
        + "error=" + error + ", "
        + "size=" + size
        + "]";
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) return true;
        if (obj == null) return false;
        if (getClass() != obj.getClass()) return false;
        Device_WriteResp other = (Device_WriteResp)obj;
        if (! java.util.Objects.equals(this.error, other.error)) return false;
        if (this.size != other.size) return false;
        return true;
    }

    @Override
    public int hashCode() {
        return XdrHashCode.hashCode(this);
    }

}
// End of Device_WriteResp.java
