/*
 * Automatically generated by jrpcgen 1.1.6 on 24-8-23 上午9:09
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
package xyz.hooy.vxi11.rpc.idl;
import org.acplt.oncrpc.*;
import java.io.IOException;

/** TODO */
public class Device_EnableSrqParms implements XdrAble {
    /** TODO */
    public Device_Link lid;
    /** TODO */
    public boolean enable;
    /** TODO */
    public byte[] handle;

    public Device_EnableSrqParms() {
    }

    public Device_EnableSrqParms(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public Device_EnableSrqParms(Device_Link lid, boolean enable, byte[] handle) {
        this.lid = lid;
        this.enable = enable;
        this.handle = handle;
    }

    @Override
    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        lid.xdrEncode(xdr);
        xdr.xdrEncodeBoolean(enable);
        xdr.xdrEncodeDynamicOpaque(handle);
    }

    @Override
    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        lid = new Device_Link(xdr);
        enable = xdr.xdrDecodeBoolean();
        handle = xdr.xdrDecodeDynamicOpaque();
    }

    @Override
    public String toString() {
        return "Device_EnableSrqParms ["
        + "lid=" + lid + ", "
        + "enable=" + enable + ", "
        + "handle=" + java.util.Arrays.toString(handle)
        + "]";
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) return true;
        if (obj == null) return false;
        if (getClass() != obj.getClass()) return false;
        Device_EnableSrqParms other = (Device_EnableSrqParms)obj;
        if (! java.util.Objects.equals(this.lid, other.lid)) return false;
        if (this.enable != other.enable) return false;
        if (! java.util.Arrays.equals(this.handle, other.handle)) return false;
        return true;
    }

    @Override
    public int hashCode() {
        return XdrHashCode.hashCode(this);
    }

}
// End of Device_EnableSrqParms.java
