/*
 * Automatically generated by jrpcgen 1.1.6 on 24-8-23 上午9:09
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
package xyz.hooy.vxi11.rpc.idl;
import org.acplt.oncrpc.*;
import java.io.IOException;

/** TODO */
public class Device_ReadResp implements XdrAble {
    /** TODO */
    public Device_ErrorCode error;
    /** TODO */
    public int reason;
    /** TODO */
    public byte[] data;

    public Device_ReadResp() {
    }

    public Device_ReadResp(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public Device_ReadResp(Device_ErrorCode error, int reason, byte[] data) {
        this.error = error;
        this.reason = reason;
        this.data = data;
    }

    @Override
    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        error.xdrEncode(xdr);
        xdr.xdrEncodeInt(reason);
        xdr.xdrEncodeDynamicOpaque(data);
    }

    @Override
    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        error = new Device_ErrorCode(xdr);
        reason = xdr.xdrDecodeInt();
        data = xdr.xdrDecodeDynamicOpaque();
    }

    @Override
    public String toString() {
        return "Device_ReadResp ["
        + "error=" + error + ", "
        + "reason=" + reason + ", "
        + "data=" + java.util.Arrays.toString(data)
        + "]";
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) return true;
        if (obj == null) return false;
        if (getClass() != obj.getClass()) return false;
        Device_ReadResp other = (Device_ReadResp)obj;
        if (! java.util.Objects.equals(this.error, other.error)) return false;
        if (this.reason != other.reason) return false;
        if (! java.util.Arrays.equals(this.data, other.data)) return false;
        return true;
    }

    @Override
    public int hashCode() {
        return XdrHashCode.hashCode(this);
    }

}
// End of Device_ReadResp.java
