/*
 * Automatically generated by jrpcgen 1.1.6 on 24-8-23 上午9:09
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
package xyz.hooy.vxi11.rpc.idl;
import org.acplt.oncrpc.HasEncoding;

/** TODO */
public enum Device_AddrFamily implements HasEncoding<Device_AddrFamily> {
    /** TODO */
    DEVICE_TCP(0),
    /** TODO */
    DEVICE_UDP(0+1);

    private final int encoding;

    private Device_AddrFamily(int encoding) {
        this.encoding = encoding;
    }

    public int getEncoding() {
        return encoding;
    }

    public HasEncoding<Device_AddrFamily>[] getValues() {
        return values();
    }

}
// End of Device_AddrFamily.java
