/*
 * Automatically generated by jrpcgen 1.1.6 on 24-8-23 上午9:09
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
package xyz.hooy.vxi11.rpc.idl;
import org.acplt.oncrpc.*;
import java.io.IOException;

/** TODO */
public class Device_DocmdParms implements XdrAble {
    /** TODO */
    public Device_Link lid;
    /** TODO */
    public Device_Flags flags;
    /** TODO */
    public int io_timeout;
    /** TODO */
    public int lock_timeout;
    /** TODO */
    public int cmd;
    /** TODO */
    public boolean network_order;
    /** TODO */
    public int datasize;
    /** TODO */
    public byte[] data_in;

    public Device_DocmdParms() {
    }

    public Device_DocmdParms(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        xdrDecode(xdr);
    }

    public Device_DocmdParms(Device_Link lid, Device_Flags flags, int io_timeout,
           int lock_timeout, int cmd, boolean network_order, int datasize,
           byte[] data_in) {
        this.lid = lid;
        this.flags = flags;
        this.io_timeout = io_timeout;
        this.lock_timeout = lock_timeout;
        this.cmd = cmd;
        this.network_order = network_order;
        this.datasize = datasize;
        this.data_in = data_in;
    }

    @Override
    public void xdrEncode(XdrEncodingStream xdr)
           throws OncRpcException, IOException {
        lid.xdrEncode(xdr);
        flags.xdrEncode(xdr);
        xdr.xdrEncodeInt(io_timeout);
        xdr.xdrEncodeInt(lock_timeout);
        xdr.xdrEncodeInt(cmd);
        xdr.xdrEncodeBoolean(network_order);
        xdr.xdrEncodeInt(datasize);
        xdr.xdrEncodeDynamicOpaque(data_in);
    }

    @Override
    public void xdrDecode(XdrDecodingStream xdr)
           throws OncRpcException, IOException {
        lid = new Device_Link(xdr);
        flags = new Device_Flags(xdr);
        io_timeout = xdr.xdrDecodeInt();
        lock_timeout = xdr.xdrDecodeInt();
        cmd = xdr.xdrDecodeInt();
        network_order = xdr.xdrDecodeBoolean();
        datasize = xdr.xdrDecodeInt();
        data_in = xdr.xdrDecodeDynamicOpaque();
    }

    @Override
    public String toString() {
        return "Device_DocmdParms ["
        + "lid=" + lid + ", "
        + "flags=" + flags + ", "
        + "io_timeout=" + io_timeout + ", "
        + "lock_timeout=" + lock_timeout + ", "
        + "cmd=" + cmd + ", "
        + "network_order=" + network_order + ", "
        + "datasize=" + datasize + ", "
        + "data_in=" + java.util.Arrays.toString(data_in)
        + "]";
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) return true;
        if (obj == null) return false;
        if (getClass() != obj.getClass()) return false;
        Device_DocmdParms other = (Device_DocmdParms)obj;
        if (! java.util.Objects.equals(this.lid, other.lid)) return false;
        if (! java.util.Objects.equals(this.flags, other.flags)) return false;
        if (this.io_timeout != other.io_timeout) return false;
        if (this.lock_timeout != other.lock_timeout) return false;
        if (this.cmd != other.cmd) return false;
        if (this.network_order != other.network_order) return false;
        if (this.datasize != other.datasize) return false;
        if (! java.util.Arrays.equals(this.data_in, other.data_in)) return false;
        return true;
    }

    @Override
    public int hashCode() {
        return XdrHashCode.hashCode(this);
    }

}
// End of Device_DocmdParms.java
