/*
 * Automatically generated by jrpcgen 1.1.6 on 24-8-23 上午9:09
 * jrpcgen is part of the "Remote Tea" ONC/RPC package for Java
 * See http://remotetea.sourceforge.net for details
 */
package xyz.hooy.vxi11.rpc.idl;
/**
 * A collection of constants used by the "vxi11" ONC/RPC program.
 */
public interface vxi11 {
    /** TODO */
    public static final int DEVICE_ASYNC_VERSION = 1;
    /** RPC procedure number of {@linkplain vxi11_DEVICE_ASYNC_CltIF#device_abort_1}
     * value = 1 */
    public static final int device_abort_1 = 1;
    /** service number of {@linkplain vxi11_DEVICE_ASYNC_CltIF}
     * value=0x0607B0 */
    public static final int DEVICE_ASYNC = 0x0607B0;
    /** TODO */
    public static final int DEVICE_CORE_VERSION = 1;
    /** RPC procedure number of {@linkplain vxi11_DEVICE_CORE_CltIF#create_link_1}
     * value = 10 */
    public static final int create_link_1 = 10;
    /** RPC procedure number of {@linkplain vxi11_DEVICE_CORE_CltIF#device_write_1}
     * value = 11 */
    public static final int device_write_1 = 11;
    /** RPC procedure number of {@linkplain vxi11_DEVICE_CORE_CltIF#device_read_1}
     * value = 12 */
    public static final int device_read_1 = 12;
    /** RPC procedure number of {@linkplain vxi11_DEVICE_CORE_CltIF#device_readstb_1}
     * value = 13 */
    public static final int device_readstb_1 = 13;
    /** RPC procedure number of {@linkplain vxi11_DEVICE_CORE_CltIF#device_trigger_1}
     * value = 14 */
    public static final int device_trigger_1 = 14;
    /** RPC procedure number of {@linkplain vxi11_DEVICE_CORE_CltIF#device_clear_1}
     * value = 15 */
    public static final int device_clear_1 = 15;
    /** RPC procedure number of {@linkplain vxi11_DEVICE_CORE_CltIF#device_remote_1}
     * value = 16 */
    public static final int device_remote_1 = 16;
    /** RPC procedure number of {@linkplain vxi11_DEVICE_CORE_CltIF#device_local_1}
     * value = 17 */
    public static final int device_local_1 = 17;
    /** RPC procedure number of {@linkplain vxi11_DEVICE_CORE_CltIF#device_lock_1}
     * value = 18 */
    public static final int device_lock_1 = 18;
    /** RPC procedure number of {@linkplain vxi11_DEVICE_CORE_CltIF#device_unlock_1}
     * value = 19 */
    public static final int device_unlock_1 = 19;
    /** RPC procedure number of {@linkplain vxi11_DEVICE_CORE_CltIF#device_enable_srq_1}
     * value = 20 */
    public static final int device_enable_srq_1 = 20;
    /** RPC procedure number of {@linkplain vxi11_DEVICE_CORE_CltIF#device_docmd_1}
     * value = 22 */
    public static final int device_docmd_1 = 22;
    /** RPC procedure number of {@linkplain vxi11_DEVICE_CORE_CltIF#destroy_link_1}
     * value = 23 */
    public static final int destroy_link_1 = 23;
    /** RPC procedure number of {@linkplain vxi11_DEVICE_CORE_CltIF#create_intr_chan_1}
     * value = 25 */
    public static final int create_intr_chan_1 = 25;
    /** RPC procedure number of {@linkplain vxi11_DEVICE_CORE_CltIF#destroy_intr_chan_1}
     * value = 26 */
    public static final int destroy_intr_chan_1 = 26;
    /** service number of {@linkplain vxi11_DEVICE_CORE_CltIF}
     * value=0x0607AF */
    public static final int DEVICE_CORE = 0x0607AF;
    /** TODO */
    public static final int DEVICE_INTR_VERSION = 1;
    /** RPC procedure number of {@linkplain vxi11_DEVICE_INTR_CltIF#device_intr_srq_1}
     * value = 30 */
    public static final int device_intr_srq_1 = 30;
    /** service number of {@linkplain vxi11_DEVICE_INTR_CltIF}
     * value=0x0607B1 */
    public static final int DEVICE_INTR = 0x0607B1;

}
// End of vxi11.java
